scrape_configs:
  - job_name: "prometheus"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "openobserve"
    metrics_path: /metrics
    static_configs:
      - targets: ["openobserve:5080"]

remote_write:
  - url: http://openobserve:5080/api/default/prometheus/api/v1/write
    queue_config:
      max_samples_per_send: 100
    basic_auth:
      username: root@example.com
      password: Complexpass#123
